#!/bin/bash
#
# Display deployment specific tags for all workers.
#
# * Add tag:
#   docker node update --label-add <TAG>=true <WORKER>
# * Remove tag:
#   docker node update --label-rm <TAG>
#

for node in $(docker node ls --filter role=worker --format '{{ .Hostname }}');
do
    tags=$(docker node inspect "$node" -f '{{.Spec.Labels}}' |\
        sed -e 's/^map\[//' -e 's/\]$//')
    printf "%s: %s\n" "$node" "$tags"
done | sort
