#!/bin/bash

IP_REGEX='((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)'
FAKE_AGENT="Mozilla/5.0 (iPhone; U; CPU iPhone OS 4_3_3 like Mac OS X; en-us) AppleWebKit/533.17.9 (KHTML, like Gecko) Version/5.0.2 Mobile/8J2 Safari/6533.18.5"
URL=http://whatismyipaddress.com/
IP_ADDR=$(curl -s -A "$FAKE_AGENT" "$URL" | grep --only-matching --max-count=1 -E $IP_REGEX | uniq)

echo "Your external IP address is : ${IP_ADDR}"
echo "Reverse DNS record is       : $(dig +short -x ${IP_ADDR})"
