set -g history-limit 30000
set -g default-terminal "tmux-256color"  # or "xterm-256color"
##OLD set -g default-terminal "screen-256color"
# remap prefix to Control + a
set -g prefix C-a
# bind 'C-a C-a' to type 'C-a'
bind C-a send-prefix
unbind C-b

# Force a reload of the config file on C-a r:
unbind r
bind-key r source-file ~/.tmux.conf \; display-message "tmux.conf reloaded."

set -g allow-rename off

# Close window
unbind k
bind k confirm-before "kill-window"

# vi is good
setw -g mode-keys vi

# Mouse scrolling
set -g mouse on
setw -g mouse on
#set -g mouse-select-pane on

# Sane scrolling
# set -g terminal-overrides 'xterm*:smcup@:rmcup@'

# Scroll with Shift+PageUp and Shift+PageDown
#bind-key -t emacs-copy -n S-PPage halfpage-up
#bind-key -t emacs-copy -n S-NPage halfpage-down


# Powerline
source "/usr/share/tmux/powerline.conf"

# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1


