#!/bin/bash
#
# Open port forwarding to an EC2 instance using AWS Systems Manager (SSM)
#
EC2_ID=${1:?"Usage: $0 <EC2_INSTANCE_ID>"}
REMOTE_PORT=22
LOCAL_PORT=${2:-1234}
PUBLIC_SSH_KEY=~/.ssh/aws_session.pub
PRIVATE_SSH_KEY=~/.ssh/aws_session
USER=ssm-user

if [ ! -f "$PUBLIC_SSH_KEY" -o ! -f "$PRIVATE_SSH_KEY" ]; then
  printf "Missing SSH key!\n"
  exit 1
fi

# Inject the public key into the EC2 instance's authorized_keys file using AWS Systems Manager (SSM)
printf "Sending the SSH key to the EC2 instance:\n"
aws ssm send-command \
  --instance-ids $EC2_ID \
  --document-name AWS-RunShellScript \
  --parameters "commands=[
    \"mkdir -p /home/$USER/.ssh\",
    \"echo '$(cat $PUBLIC_SSH_KEY)' >>/home/$USER/.ssh/authorized_keys\"
  ]" \
  --query 'Command.{CommandId:CommandId,InstanceId:InstanceIds}'

# SSH Usage
cat <<EOF
Connect:
ssh -o IdentitiesOnly=yes -i $PRIVATE_SSH_KEY -p $LOCAL_PORT $USER@127.0.0.1

Copy SCP:
scp -o IdentitiesOnly=yes -i $PRIVATE_SSH_KEY -P $LOCAL_PORT [FILES] $USER@127.0.0.1:/home/$USER/

Copy rsync:
rsync -avHPS --rsh="ssh -o IdentitiesOnly=yes -i $PRIVATE_SSH_KEY -p $LOCAL_PORT" [FILES] $USER@$127.0.0.1:/home/$USER/

Configure your ~/.ssh/config (then use only 'ssh ec2-ssm' to connect):
Host ec2-ssm
    HostName 127.0.0.1
    Port $LOCAL_PORT
    User $USER
    IdentityFile $PRIVATE_SSH_KEY
    IdentitiesOnly yes

EOF

# Create a local tunnel to the EC2 instance using SSH
aws ssm start-session \
  --target $EC2_ID \
  --document-name AWS-StartPortForwardingSession \
  --parameters "{\"portNumber\":[\"$REMOTE_PORT\"],\"localPortNumber\":[\"$LOCAL_PORT\"]}"

